title: Radek Farny | plyn
email: radek.farny@seznam.cz
description: >- 
  Radek Farny revize plynových zařízení - web
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  radek-farny
keywords: "Radek Farny, Bolešiny, Klatovy, Seznam, kontakt, plyn, revize, plynová zařízení"

# Build settings
theme: minima

plugins:
  - jekyll-sitemap