title: Revize plynu Klatovy - Radek Farny
email: radek.farny@seznam.cz
description: >- 
  Radek Farny profesionální revize plynových zařízení v Klatovech a okolí - web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://radek-farny.github.io"
github_username:  radek-farny
keywords: "Radek Farny, Bolešiny, Klatovy, Seznam, kontakt, plyn, revize, plynová zařízení, revize, plynu, revize plynu Klatovy, revize plynu v Klatovech"

# Build settings
theme: minima

plugins:
  - jekyll-sitemap